spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: publicaciones_route
              uri: http://localhost:8090
              predicates:
                - Path=/api/publicaciones/**
              filters:
                - RewritePath=/api/publicaciones/(?<segment>.*), /publicaciones/${segment}

server:
  port: 8080
