spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: publicaciones
              uri: lb://publicaciones
              predicates:
                - Path=/alojate/publicaciones/**, /alojate/uploads/**, /alojate/favoritos/** , /alojate/favoritos
              filters:
                - RewritePath=/alojate/publicaciones(?<segment>.*), /api/publicaciones${segment}
                - RewritePath=/alojate/favoritos(?<segment>.*), /api/favoritos${segment}
                - RewritePath=/alojate/uploads(?<segment>.*), /uploads${segment}
                - name: PreserveHostHeader
            - id: reservas
              uri: lb://reservas
              predicates:
                - Path=/alojate/reservas/**, /images/**
              filters:
                - RewritePath=/alojate/reservas(?<segment>.*), /api/reservas${segment}
            - id: usuarios
              uri: lb://usuarios
              predicates:
                - Path=/alojate/usuarios/**
              filters:
                - RewritePath=/alojate/usuarios(?<segment>.*), /api/usuarios${segment}
      httpclient:
        max-in-memory-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-h3xrizjs1bocf38m.us.auth0.com/
          audiences: https://localhost:8080
  http:
    codecs:
      max-in-memory-size: 100MB
auth0:
  audience: https://localhost:8080
server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.cloud.gateway.handler.predicate: TRACE


